### ISSUE TITLE
Sample fails with JSONException: No value for modules

### ISSUE THREAD

**Issue by dromosys** [Netatmo/Netatmo-API-Android#2]
org.json.JSONException: No value for modules
06-21 10:28:55.681 9827-9827/weatherstation.netatmo.com.netatmo_api_android W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
06-21 10:28:55.681 9827-9827/weatherstation.netatmo.com.netatmo_api_android W/System.err:     at org.json.JSONObject.getJSONArray(JSONObject.java:584)
06-21 10:28:55.681 9827-9827/weatherstation.netatmo.com.netatmo_api_android W/System.err:     at weatherstation.netatmo.com.netatmo_api_android.api.NetatmoUtils.parseMeasures(NetatmoUtils.java:173)
06-21 10:28:55.681 9827-9827/weatherstation.netatmo.com.netatmo_api_android W/System.err:     at weatherstation.netatmo.com.netatmo_api_android.sample.MainActivity$2.onResponse(MainActivity.java:144)
06-21 10:28:55.681 9827-9827/weatherstation.netatmo.com.netatmo_api_android W/System.err:     at weatherstation.netatmo.com.netatmo_api_android.sample.MainActivity$2.onResponse(MainActivity.java:134)

**Comment by roedll** [comment]
I experienced the same problem.
If you change the method call
https://github.com/Netatmo/Netatmo-API-Android/blob/8c93cea9628ac001fcd4fcbc37c47867b2442852/app/src/main/java/weatherstation/netatmo/com/netatmo_api_android/api/NetatmoUtils.java#L65-L66
to 
```
String id = module.getString("_id");
String name = module.optString("module_name", id);
```
it should work again...
